### ISSUE TITLE
[Beginner]: Fix HBAR Unit Symbols Not Displaying on Windows

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-cpp#172]
## 🌱 Beginner Friendly

This issue is designed to be welcoming and accessible for new contributors, including students, early-career engineers, or anyone new to open source.

Beginner Issues are typically:
- Focused on small improvements or additions  
- Limited to 1-3 files  
- Clear in scope with defined acceptance criteria

Our goal is to help contributors build confidence and familiarity with the project while making meaningful contributions.

---

## 🐞 Problem Description

When printing HBAR values on Windows (using `Hbar::toString()` or `HbarUnit::getSymbol()`), the unit symbols don't display correctly in the Windows command prompt.

**Current symbols in `HbarUnit.h`:**
```cpp
static constexpr HbarUnit TINYBAR() { return { "tℏ", 1ULL }; }
static constexpr HbarUnit MICROBAR() { return { "μℏ", 100ULL }; }
static constexpr HbarUnit MILLIBAR() { return { "mℏ", 100000ULL }; }
static constexpr HbarUnit HBAR() { return { "ℏ", 100000000ULL }; }
// etc.
```

**Problem characters:**
- `ℏ` (U+210F) - Planck constant / h-bar symbol
- `μ` (U+03BC) - Greek small letter mu

The Windows command prompt (cmd.exe) uses a limited code page by default (CP437 or CP1252) that doesn't support these Unicode characters, causing them to display as garbled text or question marks.

**Steps to reproduce:**
1. Build the SDK on Windows
2. Run `GetAccountBalanceExample` or `TransferCryptoExample`
3. Observe garbled unit symbols in the output

---

## 💡 Expected Outcome

HBAR unit symbols should display correctly on Windows. Choose one of these solutions:

**Option A: ASCII Fallback Symbols (Recommended)**

Use ASCII-compatible symbols that work on all platforms:

```cpp
static constexpr HbarUnit TINYBAR() { return { "tinybar", 1ULL }; }
static constexpr HbarUnit MICROBAR() { return { "ubar", 100ULL }; }
static constexpr HbarUnit MILLIBAR() { return { "mbar", 100000ULL }; }
static constexpr HbarUnit HBAR() { return { "hbar", 100000000ULL }; }
static constexpr HbarUnit KILOBAR() { return { "kbar", 100000000000ULL }; }
static constexpr HbarUnit MEGABAR() { return { "Mbar", 100000000000000ULL }; }
static constexpr HbarUnit GIGABAR() { return { "Gbar", 100000000000000000ULL }; }
```

**Option B: Platform-Specific Symbols**

Use Unicode on Unix, ASCII on Windows:

```cpp
#ifdef _WIN32
  static constexpr HbarUnit HBAR() { return { "hbar", 100000000ULL }; }
#else
  static constexpr HbarUnit HBAR() { return { "ℏ", 100000000ULL }; }
#endif
```

**Note:** If changing symbols, also update the regex pattern in `Hbar.cc`:

```cpp
// Current pattern uses Unicode symbols
const std::regex FROM_STRING_PATTERN("^((?:\\+|\\-)?\\d+(?:\\.\\d+)?)(\\ (tℏ|μℏ|mℏ|ℏ|kℏ|Mℏ|Gℏ))?$");
```

---

### Files to modify

1. `src/sdk/main/include/HbarUnit.h` - Update symbol strings
2. `src/sdk/main/src/Hbar.cc` - Update regex pattern to match new symbols

### Implementation steps

1. **Choose a solution approach** (Option A or B above)
2. **Update `HbarUnit.h`** with new symbols
3. **Update `Hbar.cc`** regex pattern to match new symbols
4. **Update tests** in `src/sdk/tests/unit/HbarUnitTests.cc` if they reference symbols
5. **Test on Windows** to verify symbols display correctly

### Testing

```bash
# Build and run the example
cmake --preset windows-x64-debug
cmake --build --preset windows-x64-debug
cd build/windows-x64-debug/sdk/examples/Debug
GetAccountBalanceExample.exe
```

Verify the output shows readable unit symbols.

---

## ✅ Acceptance Criteria

- [ ] HBAR unit symbols display correctly on Windows command prompt
- [ ] Symbols still display correctly on Linux/macOS
- [ ] `Hbar::fromString()` still parses values correctly
- [ ] All existing tests pass
- [ ] Unit tests updated if symbol strings changed

---

## 📋 Contribution Guide

- [ ] Comment `/assign` to request the issue
- [ ] Wait for assignment
- [ ] Fork the repository and create a branch
- [ ] Make the requested changes
- [ ] Test on Windows (or note if you need help testing)
- [ ] Sign each commit using `-s -S`
- [ ] Push your branch and open a pull request

Read [Workflow Guide](docs/training/workflow.md) for step-by-step workflow guidance.  
Read [README.md](README.md) for setup instructions.

**Pull requests cannot be merged without `S` and `s` signed commits.**
See the [Signing Guide](docs/training/signing.md).

---

## 📚 Additional Context or Resources

**Files:**
- `src/sdk/main/include/HbarUnit.h` - Symbol definitions
- `src/sdk/main/src/Hbar.cc` - toString() and fromString() implementations
- `src/sdk/tests/unit/HbarUnitTests.cc` - Unit tests

**Background:**
- Windows cmd.exe default code page doesn't support Unicode
- Windows Terminal (newer) does support Unicode, but cmd.exe is still common
- Cross-platform compatibility favors ASCII symbols

If you have questions, the community is happy to help:

https://discord.com/channels/905194001349627914/1337424839761465364
