### ISSUE TITLE
[Beginner]: Ensure Generated Transaction IDs Are Unique

### ISSUE THREAD

**Issue by thenswan** [hiero-ledger/hiero-sdk-cpp#499]
## 🌱 Beginner Friendly

This issue is designed to be welcoming and accessible for new contributors, including students, early-career engineers, or anyone new to open source.

Beginner Issues are typically:
- Focused on small improvements or additions  
- Limited to 1-3 files  
- Clear in scope with defined acceptance criteria

Our goal is to help contributors build confidence and familiarity with the project while making meaningful contributions.

---

## 🐞 Problem Description

The `TransactionId::generate()` method can produce **duplicate transaction IDs** when called rapidly in succession.

**Current implementation:**

```cpp
// src/sdk/main/src/TransactionId.cc
TransactionId TransactionId::generate(const AccountId& accountId)
{
  return TransactionId(accountId, std::chrono::system_clock::now());
}
```

The problem is that `std::chrono::system_clock::now()` has limited resolution. When generating many transaction IDs faster than the clock resolution (typically microseconds or nanoseconds depending on platform), multiple IDs will have identical timestamps, making them duplicates.

This same bug was found in the Java SDK ([issue #1557](https://github.com/hashgraph/hedera-sdk-java/issues/1557)) and fixed in [PR #1587](https://github.com/hashgraph/hedera-sdk-java/pull/1587).

---

## 💡 Expected Outcome

Modify `TransactionId::generate()` to guarantee unique timestamps by using a monotonic approach that ensures each generated timestamp is strictly greater than the previous one.

**Solution approach (from Java fix):**
1. Track the last generated timestamp using a thread-safe atomic variable
2. When generating a new ID:
   - Get current time
   - If current time <= last time, use last time + 1 nanosecond
   - Update the last time tracker
   - Return the new unique timestamp

---

### File to modify

`src/sdk/main/src/TransactionId.cc`

### Implementation steps

1. **Add a static atomic variable** to track the last generated timestamp:

```cpp
#include <atomic>

namespace
{
// Tracks the last generated timestamp to ensure uniqueness
std::atomic<int64_t> lastGeneratedNanos{0};
} // anonymous namespace
```

2. **Modify the `generate()` function** to ensure monotonic timestamps:

```cpp
TransactionId TransactionId::generate(const AccountId& accountId)
{
  // Get current time in nanoseconds since epoch
  auto now = std::chrono::system_clock::now();
  auto nowNanos = std::chrono::duration_cast<std::chrono::nanoseconds>(
    now.time_since_epoch()).count();
  
  // Ensure monotonically increasing timestamp
  int64_t lastNanos = lastGeneratedNanos.load();
  int64_t newNanos;
  do {
    newNanos = (nowNanos <= lastNanos) ? lastNanos + 1 : nowNanos;
  } while (!lastGeneratedNanos.compare_exchange_weak(lastNanos, newNanos));
  
  // Convert back to time_point
  auto validStart = std::chrono::system_clock::time_point(
    std::chrono::nanoseconds(newNanos));
  
  return TransactionId(accountId, validStart);
}
```

3. **Add a uniqueness test** in `src/sdk/tests/unit/TransactionIdUnitTests.cc`:

```cpp
TEST_F(TransactionIdUnitTests, GenerateUniqueTransactionIds)
{
  // Given
  const size_t count = 100000;
  std::vector<TransactionId> ids;
  ids.reserve(count);
  
  // When - generate many IDs rapidly
  for (size_t i = 0; i < count; ++i)
  {
    ids.push_back(TransactionId::generate(getTestAccountId()));
  }
  
  // Then - all IDs should be unique
  std::set<std::chrono::system_clock::time_point> timestamps;
  for (const auto& id : ids)
  {
    EXPECT_TRUE(timestamps.insert(id.mValidTransactionTime).second)
      << "Duplicate timestamp found";
  }
}
```

### Include additions

You may need to add these includes to `TransactionId.cc`:

```cpp
#include <atomic>
```

And to the test file:

```cpp
#include <set>
#include <vector>
```

---

## ✅ Acceptance Criteria

- [ ] `TransactionId::generate()` produces unique IDs even when called rapidly
- [ ] Implementation is thread-safe (uses atomic operations)
- [ ] Unit test added that generates 100K+ IDs and verifies uniqueness
- [ ] All existing tests continue to pass
- [ ] Code follows existing style conventions

---

## 📋 Contribution Guide

- [ ] Comment `/assign` to request the issue
- [ ] Wait for assignment
- [ ] Fork the repository and create a branch
- [ ] Set up the project using the instructions in `README.md`
- [ ] Make the requested changes
- [ ] Run unit tests: `ctest --test-dir build/<preset> -R TransactionId`
- [ ] Sign each commit using `-s -S`
- [ ] Push your branch and open a pull request

**Pull requests cannot be merged without `S` and `s` signed commits.**
See the [Signing Guide](docs/training/signing.md).

---

## 📚 Additional Context or Resources

**Reference:**
- Java SDK issue: https://github.com/hashgraph/hedera-sdk-java/issues/1557
- Java SDK fix: https://github.com/hashgraph/hedera-sdk-java/pull/1587

**Files:**
- `src/sdk/main/src/TransactionId.cc` - Implementation
- `src/sdk/main/include/TransactionId.h` - Header (no changes needed)
- `src/sdk/tests/unit/TransactionIdUnitTests.cc` - Tests

If you have questions, the community is happy to help:

https://discord.com/channels/905194001349627914/1337424839761465364

**Comment by SimiHunjan** [comment]
Research issue
