### ISSUE TITLE
Add `Windows` and `MacOS` builds to CI/CD -- convert to epic

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-cpp#691]
We currently have `Linux` builds being built in our runners for PRs and merges. We should add cross-compiled `Windows` and `MacOS` builds as well to this so we can have all builds in our CI/CD pipelines and not reliant on manual builds to generate releases.
```[tasklist]
### Tasks
- [ ] Research Windows crossbuild using xwin
- [ ] Research mingw32 for Windows builds
- [ ] Research VCPKG compatiblity for crossbuilding
- [ ] Research VCPKG binary caching
- [ ] Research Windows runner images
- [ ] Decide on Windows build approach
- [ ] Research MacOS crossbuild
- [ ] Decide on MacOS build approach
```

**Comment by rbarkerSL** [comment]
Cross compile for macOS and windows using docker linux cross-compile steps that are being implemented in the hedera-cryptography repository

**Comment by mishomihov00** [comment]
I've tried multiple approaches for windows cross-compiling, but for unfortunately none of them were successful. I've contacted Jendrik for some help as he is handling a similar topic in the hedera-cryptography repository.

**Comment by mishomihov00** [comment]
@rbarkerSL Please advise on the next steps.

**Comment by mishomihov00** [comment]
After a sync with a colleague from sdk-cpp regarding the cross-compiling I think it would be better to use native Windows runner, instead of trying to achieve cross-compiling.

Some benefits to this approach:
- A native Windows runner requires less complex setup compared to a cross-compilation environment, which often involves configuring a toolchain. The complexity of development work for setting this up may not prove worth it.

- All Windows-specific libraries are readily available and fully compatible without requiring workarounds to find suitable Linux equivalents + Applications can directly interact with Windows APIs without needing conditional compilation or compatibility layers

- Building directly on Windows can be faster, as there’s no additional overhead from cross-compilation processes. C++ SDK builds are slow enough as is. Protobufs for the C++ SDK will become in house soon as the hedera-protobufs-cpp will get deprecated as the protobuf definitions are getting moved to  the services repo.

- Easier to integrate testing. Testing on a native runner ensures that the application behaves as expected in the target environment, reducing the risk of platform-specific bugs that might go unnoticed in cross-compilation

`Note`: This points also apply for MacOS building.

If using a windows runner is not an option, I think someone else with significantly more knowledge on cross-compiling cpp projects should first identify what configurations are needed, describe them and after that I can add the steps into a workflow.

**Comment by mishomihov00** [comment]
Successful build on a windows runner: https://github.com/hashgraph/hedera-sdk-cpp/actions/runs/11479502413/job/31945943063?pr=803

**Comment by mishomihov00** [comment]
Example of a current workflow using Windows and MacOS runners: https://github.com/hashgraph/hedera-cryptography/blob/1b49f3accb41ac01c9c7994d04c46947c7bc0e20/.github/workflows/build.yml#L92

**Comment by mishomihov00** [comment]
There seems to be an issue with the hedera local node starting on windows runners. I've raised an issue here - https://github.com/hashgraph/hedera-local-node/issues/806

**Comment by mishomihov00** [comment]
@rbarkerSL As described here - https://github.com/hashgraph/hedera-local-node/issues/806#issuecomment-2446317569, the building on windows runners is not possible, because they do not support WSL2. We should discuss this further.

**Comment by rbarkerSL** [comment]
I'd like to get @rwalworth to provide input here.

**Comment by rwalworth** [comment]
Getting at least the builds going here would prove very beneficial; I have to manually do them for each release, which can then delay our release schedule if I'm out. I think we should go ahead and get the builds integrated. Do we know if there's a plan for github runners to eventually support WSL2?

**Comment by mishomihov00** [comment]
The building is possible yes. Also I recently found this action which might allow us to run the tests - https://github.com/vedantmgoyal9/setup-wsl2
