### ISSUE TITLE
[Intermediate]: Add Documentation and Tests for `-1` (Unlimited) `maxAutomaticTokenAssociations` in Contract Transactions

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hiero-ledger/hiero-sdk-cpp#720]
## 🧩 Intermediate Friendly

This issue is a good fit for contributors who are already familiar with the
Hiero C++ SDK and feel comfortable navigating the codebase.

Intermediate Issues often involve:
- Exploring existing implementations  
- Understanding how different components work together  
- Making thoughtful changes that follow established patterns  

The goal is to support deeper problem-solving while keeping the task clear,
focused, and enjoyable to work on.

---

## 🐞 Problem Description

Per HIP-904, a value of `-1` for `maxAutomaticTokenAssociations` means **unlimited automatic token associations**.

The `AccountCreateTransaction` class already documents this behavior:

```cpp
* @param associations The desired maximum amount of token associations for the new account. A value of -1 means
*                     the new account can have unlimited automatic token associations.
```

However, the following contract-related classes are **missing this documentation**:

- `ContractCreateTransaction.h`
- `ContractUpdateTransaction.h`
- `ContractCreateFlow.h`

Additionally, while `AccountCreateTransaction` has integration tests using `-1`, the **contract classes have no tests** verifying that `-1` (unlimited) works correctly.

**Verification:** This functionality is fully supported in the consensus node:
- `ContractUpdateHandler.java` defines `UNLIMITED_AUTOMATIC_ASSOCIATIONS = -1`
- Integration tests in the consensus node use `@Contract(maxAutoAssociations = -1)` extensively
- The C++ SDK already accepts `-1` (the type is `int32_t`), it just lacks documentation and tests

---

## 💡 Expected Outcome

This issue has three parts:

### Part 1: Documentation Updates
Add documentation about `-1` meaning unlimited to the three contract classes, matching the style used in `AccountCreateTransaction`.

### Part 2: Unit Tests
Add unit tests verifying that `-1` is accepted by `setMaxAutomaticTokenAssociations()` and correctly round-trips through serialization.

### Part 3: Integration Tests
Add integration tests verifying that contracts created/updated with `-1` can auto-associate with tokens without hitting a limit.

All changes should:
- Follow existing patterns in the codebase
- Not modify any existing behavior
- Match the style and conventions already established

---

### Part 1: Documentation Updates

Update the `@param` descriptions in three header files:

| File | Location | Current | Updated |
|------|----------|---------|---------|
| `ContractCreateTransaction.h` | ~line 182 | `The maximum amount of token associations for the new smart contract instance.` | Add: `A value of -1 means the new smart contract instance can have unlimited automatic token associations.` |
| `ContractUpdateTransaction.h` | ~line 109 | `The desired new maximum amount of token associations for the contract.` | Add: `A value of -1 means the contract can have unlimited automatic token associations.` |
| `ContractCreateFlow.h` | ~line 131 | `The maximum amount of token associations for the new smart contract instance.` | Add: `A value of -1 means the new smart contract instance can have unlimited automatic token associations.` |

### Part 2: Unit Tests

Add tests verifying `-1` is accepted. Look at existing tests in these files for patterns:

| File | Existing Test | New Test to Add |
|------|---------------|-----------------|
| `ContractCreateTransactionUnitTests.cc` | `GetSetMaxAutomaticTokenAssociations` (~line 311) | `GetSetMaxAutomaticTokenAssociationsUnlimited` |
| `ContractUpdateTransactionUnitTests.cc` | `GetSetMaxAutomaticTokenAssociations` (~line 245) | `GetSetMaxAutomaticTokenAssociationsUnlimited` |
| `ContractCreateFlowUnitTests.cc` | `GetSetMaxAutomaticTokenAssociations` (~line 153) | `GetSetMaxAutomaticTokenAssociationsUnlimited` |

Each new test should:
- Set `-1` using `setMaxAutomaticTokenAssociations(-1)`
- Verify `getMaxAutomaticTokenAssociations()` returns `-1`

### Part 3: Integration Tests

**Note:** Integration tests require running a local test environment.

Add integration tests verifying unlimited associations work. Reference files:
- `TransferTransactionIntegrationTests.cc` - Uses `-1` with accounts
- `TokenAirdropTransactionIntegrationTests.cc` (line ~90) - Uses `-1` with accounts

| File | Test to Add | Description |
|------|-------------|-------------|
| `ContractCreateTransactionIntegrationTests.cc` | `CreateContractWithUnlimitedTokenAssociations` | Create contract with `-1`, query info, verify `mMaxAutomaticTokenAssociations == -1` |
| `ContractUpdateTransactionIntegrationTests.cc` | `UpdateContractToUnlimitedTokenAssociations` | Create contract with normal max, update to `-1`, verify the change |

---

## ✅ Acceptance Criteria

To help get this change merged smoothly:

- [ ] **Documentation:** All three header files have updated `@param` descriptions
- [ ] **Unit Tests:** New unit tests verify `-1` is accepted for all three classes
- [ ] **Integration Tests:** New integration tests verify unlimited associations work
- [ ] **Behavior:** No other SDK behavior or API changes
- [ ] **Tests:** All existing and new tests pass
- [ ] **CI:** All CI checks pass
- [ ] **Review:** All code review feedback addressed

---

## 📋 Contribution Guide

To help your contribution go as smoothly as possible, we recommend following these steps:

- [ ] Comment `/assign` to request the issue
- [ ] Wait for assignment
- [ ] Fork the repository and create a branch
- [ ] Set up the project using the instructions in `README.md`
- [ ] Make the requested changes
- [ ] Sign each commit using `-s -S`
- [ ] Push your branch and open a pull request

Read [Workflow Guide](docs/training/workflow.md) for step-by-step workflow guidance.  
Read [README.md](README.md) for setup instructions.

❗ Pull requests **cannot be merged** without `S` and `s` signed commits.  
See the [Signing Guide](docs/training/signing.md).

---

### Reference Files

**Documentation pattern to follow:**
- `src/sdk/main/include/AccountCreateTransaction.h` (line ~167)

**Unit test patterns to follow:**
- `src/sdk/tests/unit/ContractCreateTransactionUnitTests.cc` (line ~311)
- `src/sdk/tests/unit/AccountCreateTransactionUnitTests.cc` (line ~316)

**Integration test patterns to follow:**
- `src/sdk/tests/integration/TransferTransactionIntegrationTests.cc` (uses `-1` with accounts)
- `src/sdk/tests/integration/TokenAirdropTransactionIntegrationTests.cc` (line ~90)

### Background

**HIP-904:** This HIP introduced unlimited automatic token associations with `-1`.

**Consensus Node Verification:** The functionality is fully implemented:
- `ContractUpdateHandler.java` defines `UNLIMITED_AUTOMATIC_ASSOCIATIONS = -1`
- Many integration tests use `@Contract(maxAutoAssociations = -1)`

If you have questions, the community is happy to help:

https://discord.com/channels/905194001349627914/1337424839761465364
