### ISSUE TITLE
[Beginner]: Add `removeSignature` and `removeAllSignatures` Methods

### ISSUE THREAD

**Issue by jbair06** [hiero-ledger/hiero-sdk-cpp#771]
## 🌱 Beginner Friendly

This issue is a great way to get started contributing to the Hiero C++ SDK!

Beginner Issues help you learn the codebase while making meaningful contributions. They're scoped to be clear, focused, and approachable — even if you're new to the project.

---

## 👾 Description of the Issue

Once a signature has been added to a transaction via `addSignature()`, there is no way to remove it. This can be problematic in several scenarios:

1. **Transaction too large**: When a signing account has a large keylist with many thresholds, adding all signatures might result in a transaction that's too large to submit. Users need to remove excess signatures to keep only the minimum required.

2. **Signature revocation**: If a signer decides to revoke their signature, they currently have to recreate the entire transaction and re-add all other signatures.

---

## 💡 Proposed Solution

Add two new methods to the `Transaction` class:

### 1. `removeSignature(publicKey)`

Removes all signatures associated with a specific public key:

```cpp
std::vector<std::vector<std::byte>> removeSignature(const std::shared_ptr<PublicKey>& publicKey);
```

**Behavior:**
- Throws if the transaction is not frozen
- Throws if the public key has not signed the transaction
- Removes matching signatures from all signed transactions
- Returns the removed signatures
- Updates internal tracking (`mSignatories`, etc.)

### 2. `removeAllSignatures()`

Removes all signatures from the transaction:

```cpp
std::map<std::shared_ptr<PublicKey>, std::vector<std::vector<std::byte>>> removeAllSignatures();
```

**Behavior:**
- Throws if the transaction is not frozen
- Clears all signature pairs from all signed transactions
- Returns the removed signatures grouped by public key
- Clears internal tracking

---

## 👩‍💻 Implementation Steps

1. **Add method declarations** to `src/sdk/main/include/Transaction.h`

2. **Implement `removeSignature()`** in `src/sdk/main/src/Transaction.cc`:
   - Check if frozen (throw `IllegalStateException` if not)
   - Check if public key exists in `mSignatories` (throw if not)
   - Iterate through `mSignedTransactions` and remove matching `sigpair` entries
   - Remove from `mSignatories` and `mPrivateKeys`
   - Clear `mTransactions` (will be regenerated)
   - Return removed signatures

3. **Implement `removeAllSignatures()`** in `src/sdk/main/src/Transaction.cc`:
   - Check if frozen
   - Collect all signatures by public key
   - Clear all `sigpair` entries from all signed transactions
   - Clear `mSignatories` and `mPrivateKeys`
   - Clear `mTransactions`
   - Return collected signatures

4. **Add unit tests** to `src/sdk/tests/unit/TransactionUnitTests.cc`

---

## ✅ Acceptance Criteria

- [ ] `removeSignature(publicKey)` implemented
- [ ] `removeAllSignatures()` implemented
- [ ] Unit tests for both methods
- [ ] Throws appropriate exceptions for error cases
- [ ] Returns removed signatures in correct format
- [ ] Existing tests continue to pass

---

## 📋 Step-by-Step Contribution Guide

- [ ] Comment `/assign` to request the issue
- [ ] Wait for assignment
- [ ] Fork the repository and create a branch
- [ ] Set up the project using the instructions in `README.md`
- [ ] Make the requested changes
- [ ] Sign each commit using `-s -S`
- [ ] Push your branch and open a pull request

Read [Workflow Guide](docs/training/workflow.md) for step-by-step workflow guidance.  
Read [README.md](README.md) for setup instructions.

❗ Pull requests **cannot be merged** without `S` and `s` signed commits.  
See the [Signing Guide](docs/training/signing.md).

---

### Reference Implementation (JS SDK)

The JavaScript SDK has already implemented this feature:

| File | Lines | Description |
|------|-------|-------------|
| `hiero-sdk-js/src/transaction/Transaction.js` | 1121-1157 | `removeSignature(publicKey)` |
| `hiero-sdk-js/src/transaction/Transaction.js` | 1167-1188 | `removeAllSignatures()` |

Original JS SDK PR: https://github.com/hashgraph/hedera-sdk-js/pull/2491

### C++ SDK Files to Modify

| File | Changes |
|------|---------|
| `src/sdk/main/include/Transaction.h` | Add method declarations |
| `src/sdk/main/src/Transaction.cc` | Implement methods |
| `src/sdk/tests/unit/TransactionUnitTests.cc` | Add unit tests |

### Internal Data Structures

The Transaction class uses these relevant members (in `TransactionImpl`):

```cpp
std::vector<proto::SignedTransaction> mSignedTransactions;  // Signed transactions per node
std::unordered_map<std::shared_ptr<PublicKey>, 
                   std::function<std::vector<std::byte>(...)>> mSignatories;  // Signers
std::unordered_map<std::shared_ptr<PublicKey>, 
                   std::shared_ptr<PrivateKey>> mPrivateKeys;  // Associated keys
```

### Existing Pattern to Follow

Look at `addSignature()` implementation (Transaction.cc:476-509) for patterns on:
- Checking frozen state
- Modifying `mSignedTransactions`
- Updating `mSignatories`
- Clearing `mTransactions` for regeneration

### Test Cases

1. Remove signature from single-signer transaction
2. Remove one signature from multi-signer transaction
3. Remove signature that doesn't exist (should throw)
4. Remove signature from unfrozen transaction (should throw)
5. Remove all signatures and verify transaction state
6. Verify returned signatures match what was added

If you have questions while working on this issue, feel free to ask!

You can reach the community and maintainers here:
[Hiero-SDK-C++ Discord](https://discord.com/channels/905194001349627914/1337424839761465364)

Whether you need help finding the right file, understanding existing code, or confirming your approach — we're happy to help.

**Comment by TikTorchic18** [comment]
Hi, could you unassign me from this issue? I don't think I'm ready for this just yet.
